name: Release - Docker (Manual)

on:
  workflow_dispatch:
    inputs:
      release_id:
        description: |
          Release ID.
          You can find it using the command:
            curl -s \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/$OWNER/$REPO/releases | \
              jq '.[] | { name: .name, id: .id }'
        required: true
        type: string
      production_image:
        description: "True for an image for the final release or false for an rc image"
        required: true
        type: boolean
        default: false
      registry:
        description: "Container registry"
        required: true
        type: string
        default: docker.io
      owner:
        description: Owner of the container image repo
        required: true
        type: string
        default: parity

env:
  RELEASE_ID: ${{ inputs.release_id }}
  ENGINE: docker
  REGISTRY: ${{ inputs.registry }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_OWNER: ${{ inputs.owner || github.repository_owner }}
  REPO: ${{ github.repository }}

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Prepare temp folder
        run: |
          TMP=$(mktemp -d)
          echo "TMP=$TMP" >> "$GITHUB_ENV"
          pwd
          ls -al "$TMP"

      - name: Fetch lib.sh from polkadot repo
        working-directory: ${{ env.TMP }}
        run: |
            curl -O -L \
                -H "Accept: application/vnd.github.v3.raw" \
                https://raw.githubusercontent.com/paritytech/polkadot/master/scripts/ci/common/lib.sh

            chmod a+x lib.sh
            ls -al

      - name: Fetch all artifacts
        run: |
            . ${TMP}/lib.sh
            fetch_release_artifacts
            cp -f ${TMP}/lib.sh release-artifacts/

      - name: Cache the artifacts
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
            key: artifacts-${{ github.sha }}
            path: |
                ./release-artifacts/**/*

  build-container:
    runs-on: ubuntu-latest
    needs: fetch-artifacts

    strategy:
      matrix:
        binary: ["polkadot-parachain"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Get artifacts from cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          key: artifacts-${{ github.sha }}
          fail-on-cache-miss: true
          path: |
            ./release-artifacts/**/*

      - name: Check sha256 ${{ matrix.binary }}
        working-directory: ./release-artifacts
        run: |
          . ./lib.sh

          echo "Checking binary ${{ matrix.binary }}"
          check_sha256 ${{ matrix.binary }} && echo "OK" || echo "ERR"

      - name: Check GPG ${{ matrix.binary }}
        working-directory: ./release-artifacts
        run: |
          . ./lib.sh
          import_gpg_keys
          check_gpg ${{ matrix.binary }}

      - name: Fetch commit and tag
        id: fetch_refs
        run: |
            is_final=${{ inputs.production_image }}

            if [ "${is_final}" != "true" ]; then
                release=release-${{ inputs.release_id }} && \
                echo "release=${release}" >> $GITHUB_OUTPUT

                commit=$(git rev-parse --short HEAD) && \
                echo "commit=${commit}" >> $GITHUB_OUTPUT


                tag=$(git name-rev --tags --name-only $(git rev-parse HEAD)) && \
                [ "${tag}" != "undefined" ] && echo "tag=${tag}" >> $GITHUB_OUTPUT || \
                echo "No tag, doing without"
            else
                semver=$( echo $VERSION | cut -f1 -d- )
                echo "tag=latest" >> $GITHUB_OUTPUT
                echo "semver=${semver}" >> $GITHUB_OUTPUT
            fi

      - name: Build Injected Container image for ${{ matrix.binary }}
        env:
            BIN_FOLDER: ./release-artifacts
            BINARY: ${{ matrix.binary }}
            TAGS: ${{join(steps.fetch_refs.outputs.*, ',')}}
        run: |
          for bin in $BIN_FOLDER/$BINARY; do
            chmod a+x $BIN_FOLDER/$bin
          done
          
          echo "Building container for ${{ matrix.binary }}"
          ./docker/scripts/build-injected-image.sh

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Container image for ${{ matrix.binary }}
        id: docker_push
        env:
          BINARY: ${{ matrix.binary }}
        run: |
          $ENGINE images | grep ${BINARY}
          $ENGINE push --all-tags ${REGISTRY}/${DOCKER_OWNER}/${BINARY}

      - name: Check version for the published image for ${{ matrix.binary }}
        env:
          BINARY: ${{ matrix.binary }}
          RELEASE_TAG: ${{ steps.fetch_refs.outputs.release }}
        run: |
          echo "Checking tag ${RELEASE_TAG} for image ${REGISTRY}/${DOCKER_OWNER}/${BINARY}"
          $ENGINE run -i ${REGISTRY}/${DOCKER_OWNER}/${BINARY}:${RELEASE_TAG} --version
